"""Precompute SVM decision-function grids for the Chapter 06 interactive demo.

Run from ml-site/:  .venv/bin/python scripts/demo_ch06.py
Output: docs/assets/js/demos/ch06-svm-data.js  (defines window.CH06_SVM_DATA)

The browser only switches between precomputed grids; no ML runs in JS.
Decision values are clipped to [-2, 2] and stored as integers (x50) to keep the file small.
"""
import json
from pathlib import Path

import numpy as np
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

OUT = Path(__file__).resolve().parent.parent / "docs" / "assets" / "js" / "demos" / "ch06-svm-data.js"
RS = 42
N_GRID = 45
C_LIST = [0.1, 1, 10, 100]
GAMMA_LIST = [0.1, 0.5, 1, 5, 20]

X, y = make_moons(n_samples=160, noise=0.3, random_state=RS)
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.4, stratify=y, random_state=RS)

pad = 0.4
xs = np.linspace(X[:, 0].min() - pad, X[:, 0].max() + pad, N_GRID)
ys = np.linspace(X[:, 1].min() - pad, X[:, 1].max() + pad, N_GRID)
xx, yy = np.meshgrid(xs, ys)
grid = np.c_[xx.ravel(), yy.ravel()]


def encode(clf):
    z = clf.decision_function(grid)
    z = np.clip(z, -2, 2)
    return [int(v) for v in np.round(z * 50)]


def fit(kernel, C, gamma=None):
    kw = {"kernel": kernel, "C": C}
    if gamma is not None:
        kw["gamma"] = gamma
    clf = SVC(**kw).fit(X_tr, y_tr)
    return {
        "z": encode(clf),
        "sv": [int(i) for i in clf.support_],
        "train": round(float(clf.score(X_tr, y_tr)), 3),
        "test": round(float(clf.score(X_te, y_te)), 3),
    }


models = {}
for ci, C in enumerate(C_LIST):
    models[f"linear_{ci}"] = fit("linear", C)
    for gi, g in enumerate(GAMMA_LIST):
        models[f"rbf_{ci}_{gi}"] = fit("rbf", C, g)

data = {
    "x": [round(float(v), 3) for v in xs],
    "y": [round(float(v), 3) for v in ys],
    "scale": 50,
    "C": C_LIST,
    "gamma": GAMMA_LIST,
    "train": {"x1": np.round(X_tr[:, 0], 3).tolist(), "x2": np.round(X_tr[:, 1], 3).tolist(), "y": y_tr.tolist()},
    "test": {"x1": np.round(X_te[:, 0], 3).tolist(), "x2": np.round(X_te[:, 1], 3).tolist(), "y": y_te.tolist()},
    "models": models,
}

OUT.parent.mkdir(parents=True, exist_ok=True)
payload = json.dumps(data, separators=(",", ":"))
OUT.write_text(
    "// Auto-generated by scripts/demo_ch06.py - do not edit by hand.\n"
    f"window.CH06_SVM_DATA={payload};\n",
    encoding="utf-8",
)
print("saved", OUT, f"{OUT.stat().st_size / 1024:.1f} KB")
for k in ["rbf_1_0", "rbf_1_2", "rbf_3_4", "linear_1"]:
    m = models[k]
    print(k, "train", m["train"], "test", m["test"], "nSV", len(m["sv"]))
